### ISSUE TITLE
order of Tags in group is wrong

### ISSUE THREAD

**Issue by bobstar6** [electronifie/node-quickfix#2]
I think the developer of node_quickfix did not notice that the order of Tags in group is important.

In FIX protocol, If the order of Tags in group is wrong, the request will be rejected and get the response
"Out of order repeating group members"

![2015-02-10 12 11 11](https://cloud.githubusercontent.com/assets/9458206/6121418/f783a7be-b11d-11e4-91e6-e29e73e3d006.png)

As my example,
```js
          groups: [{
            'index': 146,
            'delim': 55,
            'entries': [{
              '55': 'BITCOIN',
              '48': 'BITCOIN.C',
              '22': 111
            }]
```
The correct send order is 55 48 22 (FIX Protocol need this order)

But node_quickfix send them in this order 55 22 48. 

Why 55 comes before 22 ? Because delim=55, and If I set delim=48 node_quickfix will send them in this order48 22 55

How quickfix_ruby resolve this problem?

In Quickfix_ruby https://github.com/quickfix/quickfix/blob/master/src/ruby/quickfix44.rb#L571
They set the order of group Tags in initializer

Sorry , I’m not familiar with these source code below, But I think the developer can fix this problem here.
 https://github.com/electronifie/node-quickfix/blob/master/src/FixMessageUtil.h#L93

**Comment by bobstar6** [comment]
I found the problem

I must set the params order[]

![2015-02-10 3 30 37](https://cloud.githubusercontent.com/assets/9458206/6123821/10bb2940-b142-11e4-86aa-b27a811a10db.png)

https://github.com/electronifie/node-quickfix/blob/master/src/FixMessageUtil.h#L99
I tried this, but it doesn't work
![2015-02-10 3 35 14](https://cloud.githubusercontent.com/assets/9458206/6123827/203135e0-b142-11e4-90ed-9f2f64a38a71.png)

**Comment by bobstar6** [comment]
I have resolved my problem by add 0 the end of foo
'''c
foo[] = { 55, 65, 48, 22, 0 };
'''
And It works.I think because there is no Tag0 in Quickfix Protocol(the first tag is 1 means Account), so the C++ code put '0' as the end of Array "order".

node_quickfix is supercool, and hope the developer to implement this order API

**Comment by kdeol** [comment]
Hi Bob,

I believe Quickfix orders the tags according to your data dictionary, otherwise it orders them numerically (except for the delimiter). Do you have the following in your properties file?

```
UseDataDictionary=Y
DataDictionary=<path to FIX Dictionary XML>
```

If you do, is the order correct in it?

If all that checks out, it may in fact be a problem with the groups being dynamic and thus, Quickfix not having information about what type the group should be and ordering numerically as a default.

**Comment by bobstar6** [comment]
Hi kdeol,

I think maybe you should ref quickfix_ruby's implement
https://github.com/quickfix/quickfix/blob/master/src/ruby/quickfix44.rb#L571
quickfix_ruby add a Class called "Quickfix::Group"
its initializer method can arrange the order of group tags


And yes I have added the DataDictionary File (FIX44.xml) and the correct properties file like this
```
UseDataDictionary=Y
DataDictionary=FIX44.xml
```

And I have checked the DataDictionary, the order is correct 55 48 22, you can see it in the following picture.
```
NoRelatedSym = 146
Symbol = 55
SecurityID = 48
SecurityIDSource = 22
```

![2015-02-11 10 28 34](https://cloud.githubusercontent.com/assets/9458206/6140926/4205f74a-b1d9-11e4-92ad-eaa912eef900.png)

![2015-02-11 10 31 29](https://cloud.githubusercontent.com/assets/9458206/6140931/4e0848ea-b1d9-11e4-857b-58251979d930.png)

so I think Quickfix do not think that arrangement order of group tags is his work.

**Comment by mobiletradingpartners** [comment]
Please see https://github.com/electronifie/node-quickfix/pull/41
