### ISSUE TITLE
Problem (and a possible solution) for getters/setters for session sequence numbers in 1.0.0

### ISSUE THREAD

**Issue by andrija-hers** [electronifie/node-quickfix#25]
Hi,

I had a problem with using getters/setters for session sequence numbers, like

```javascript
    var session = this.fix.getSession(this.fix.getSessions()[0]);
      console.log('session', session.getSessionID(), 'is enabled', session.isEnabled());
      console.log('sender seq num', session.senderSeqNum, 'target seq num', session.targetSeqNum);
      session.senderSeqNum = 3115;

```
The situation is that the method call `isEnabled` runs ok, and returns `true`.
But invocation of any getter/setter results in assert failing and program crashing.

However, it turns out that if in `NAN_GETTER` code I use `args.This()` instead of `args.Holder()` the program works just fine, both for setters and getters.

Would anyone be interested in some PR?

**Comment by mateodelnorte** [comment]
Sure thing! Thanks Andrija. We'll test against a working system as well.

**Comment by andrija-hers** [comment]
Still nobody interested in #26? Perhaps it's because it is not on the master branch (bond_version branch, node v 0.12 affected)?
