### ISSUE TITLE
crash while starting an initiator. 

### ISSUE THREAD

**Issue by yuanzhanghu** [electronifie/node-quickfix#31]
node fixclient.js 
FIX Initiator Started
node: ../node_modules/nan/nan_object_wrap.h:33: static T* Nan::ObjectWrap::Unwrap(v8::Local<v8::Object>) [with T = FixSession]: Assertion `object->InternalFieldCount() > 0' failed.
Aborted (core dumped)

I was using initiatorExample.js to connect fxcm demo FIX server.

**Comment by mateodelnorte** [comment]
Hi @yuanzhanghu. Can you paste or point us to a code example?

**Comment by antoniobusrod** [comment]
@mateodelnorte try to execute `node examples/acceptorExample.js`
