### ISSUE TITLE
Crash while starting acceptor example

### ISSUE THREAD

**Issue by antoniobusrod** [electronifie/node-quickfix#38]
```bash
$ node acceptorExample.js 
FIX Acceptor Started
node: ../node_modules/nan/nan_object_wrap.h:33: static T* Nan::ObjectWrap::Unwrap(v8::Local<v8::Object>) [with T = FixSession]: Assertion `object->InternalFieldCount() > 0' failed.
[1]    21197 abort (core dumped)  node acceptorExample.js
```

I think there is a problem in `FixSession::wrapFixSession` when returns wrapped session instance.

**Comment by theslyone** [comment]
Hi @stefankutko , great work so far with this FIX wrapper, however i also encountered the same exact problem as @antoniobusrod on both acceptor and initiator example.

nodejs: ../node_modules/nan/nan_object_wrap.h:33: static T* Nan::ObjectWrap::Unwrap(v8::Local<v8::Object>) [with T = FixSession]: Assertion `object->InternalFieldCount() > 0' failed.
Aborted (core dumped)

What might a possible solution be?

**Comment by kdeol** [comment]
It looks like there is something wrong with the `getSession()` call. If you comment out the line in the example `common.printStats(fixServer);` it works. Will look in to why this broke.

**Comment by theslyone** [comment]
@kdeol It indeed works without the getSession() call, thanks for pointing that out.

**Comment by kdeol** [comment]
Pushed a new version that should fix this error...
