### ISSUE TITLE
fatal error: 'quickfix/Session.h' file not found #include "quickfix/Session.h"         

### ISSUE THREAD

**Issue by elanamig** [electronifie/node-quickfix#43]
Hello,

Trying to install, and getting this error.  The compilation was successful.

```
./src/FixConnection.h:23:10: fatal error: 'quickfix/config.h' file not found
```

Please, help!  Thank you!

**Comment by stefankutko** [comment]
Hi @elanamig after you install quickfix locally, run the following command to make the config.h available to the build script:

`cp config.h /usr/local/include/quickfix/config.h`
