### ISSUE TITLE
Can`t logging into directly mysql database

### ISSUE THREAD

**Issue by malavshah9** [electronifie/node-quickfix#55]
I want to log directly into the mysql database stored on my server.

I had created database for quickfix by following link,
http://www.quickfixengine.org/quickfix/doc/html/generating_databases.html

I had followed setting configuration parameter from following link,
http://www.quickfixengine.org/quickfix/doc/html/configuration.html

Using linux and this node wrapper.

My Configuration file is as follows,

http://www.quickfixengine.org/quickfix/doc/html/configuration.html

Following is my configuration.

[DEFAULT] 
ConnectionType=acceptor
PersistMessages=Y  
UseDataDictionary=Y
MySQLStoreDatabase=quickfix
MySQLStoreUser=my-user
MySQLStorePassword=my-password
MySQLStoreHost=my-host
MySQLStorePort=3306
MySQLStoreUseConnectionPool=N
MySQLLogDatabase=quickfix
MySQLLogUser=my-user
MySQLLogPassword=my-pass
MySQLLogHost=my-host
MySQLLogPort=3306
MySQLLogUseConnectionPool=N
MySQLLogIncomingTable=messages_log
MySQLLogOutgoingTable=messages_log
MySQLLogEventTable=event_log
DefaultApplVerID=FIX.5.0
TransportDataDictionary=./spec/FIXT11.xml 
AppDataDictionary=./spec/FIX50.xml 
HttpAcceptPort=1234

[SESSION]  
BeginString=FIXT.1.1
SenderCompID=ACCEPTOR
TargetCompID=INITIATOR
SocketAcceptPort=3500
HeartBtInt=20
ReconnectInterval=30
StartTime=00:00:00
EndTime=23:00:00

**Comment by makarov-roman** [comment]
@malavshah9 were you able to resolve this issue?

**Comment by malavshah9** [comment]
Yes I have resolved this issue successfully.
Thanks for the help!!!
