### ISSUE TITLE
Does the send callback indicate an error condition?

### ISSUE THREAD

**Issue by ajoseps** [electronifie/node-quickfix#56]
It seems that the callback for the FIX send and sendRaw functions only trigger _HandleOKCallback_ and **not** the _HandleErrorCallback_. The reason why I suspect this is because I tried the following scenario.

```
1. Logon to FIX Session
2. Sleep before sending FIX message
3. Disconnect/Disable Internet
4. Sleep ends. Continue execution to send message
5. Callback gets triggered but the passed in value to the callback function is null
```

I also tried the success case and confirmed the passed in value of the callback is still null.

The default version of [_HandleErrorCallback_](https://github.com/nodejs/nan/blob/1a56c0a6efd4fac944cb46c30912a8e023bda7d4/nan.h#L1901) which is **not** overriden by _FixSessionAsyncWorker_ passes back an error value. The overriden _HandleOKCallback_ always passes back a [null value](https://github.com/Trumid/node-quickfix/blob/master/src/FixSession.cpp#L24). In nan's [WorkComplete](https://github.com/nodejs/nan/blob/1a56c0a6efd4fac944cb46c30912a8e023bda7d4/nan.h#L1833) function, it conditions which callback to call based on `errmsg_`. I suspect node-quickfix does not set `errmsg_` when a failure occurs.

Code Snippets I used inside my initiator:
```
console.log('sleeping for 5 seconds');
sleep(5000)
console.log('done sleeping');
this.send(req, (err) => {
    console.log(`ERROR: ${err}`);
});
```

Definition of sleep:
```
function sleep(miliseconds) {
   var currentTime = new Date().getTime();
   while (currentTime + miliseconds >= new Date().getTime()) {
   }
}
```

**Comment by askmike** [comment]
Not familiar with this lib, but your sleep function is blocking the event loop. Meaning no callbacks can fire until it (and everything in sync after it) completes. I'd look into [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout) if I were you.

**Comment by ajoseps** [comment]
That was the point of the sleep function... to halt execution until the network connection was disabled, and to fire the callbacks afterwards so that they fail to send.

Regardless, the reason why there is no error propagation is because the underlying quickfix library does not propagate send errors. I believe it stores all failed messages into a queue/buffer and just retries them indefinitely. The send function in quickfix always returns true, so the nodejs wrapper would never know if it ever failed. I was able to trigger the `HandleErrorCallback` by placing `SetErrorMessage()` into the happy path, but since there is no way to determine if a send actually failed without modifying quickfix itself, we can't really do much on the node layer. [Relevant SO](https://stackoverflow.com/questions/57438481/how-are-function-failures-propagated-for-nodejs-wrapped-c-code)

**Comment by askmike** [comment]
Apologies, misunderstood what you were trying to do.
